### ISSUE TITLE
Feature request: Ignore a line

### ISSUE THREAD

**Issue by JuergenMang** [simonkowallik/irulescan#5]
First I will thank you for this great project! I use it regularly to validate my iRules. 

I have one feature request:
It would be useful if there were a syntax to exclude the next or current line from validation.

```
#irulscan-ignore-next-line
eval ...
```

**Comment by simonkowallik** [comment]
Hi @JuergenMang, happy to hear you use irulescan successfully! irulescan doesn't scan iRules line-by-line, hence it's not a simple task to implement this feature.

What I'd suggest is to capture any findings as "acceptable" results. This is what https://github.com/marketplace/actions/irules-security-scan does for example.

**Comment by JuergenMang** [comment]
Thanks for your fast reply. I will look into that.
